package com.pos.inventsight.uuid;

import com.pos.inventsight.model.sql.Product;
import com.pos.inventsight.model.sql.Store;
import org.junit.jupiter.api.Test;

import java.math.BigDecimal;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Simple unit test to verify UUID functionality without Spring context
 */
public class SimpleUuidTest {

    @Test
    public void testStoreUuidGeneration() {
        Store store = new Store();
        store.setStoreName("Test Store");
        store.setAddress("123 Test St");
        store.setCity("Test City");
        store.setState("TS");
        store.setCountry("Test Country");
        
        // UUID should be null before persistence (generated by Hibernate)
        assertNull(store.getId(), "UUID should be null before persistence");
        
        // Manually set UUID to simulate what Hibernate would do
        UUID testUuid = UUID.randomUUID();
        store.setId(testUuid);
        
        // Verify UUID is set and valid
        assertNotNull(store.getId());
        assertEquals(testUuid, store.getId());
        assertTrue(store.getId() instanceof UUID);
        
        // Verify UUID format is valid
        String uuidString = store.getId().toString();
        assertTrue(uuidString.matches("^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"));
    }

    @Test
    public void testProductUuidGeneration() {
        // Create store first and simulate persisted state
        Store store = new Store("Test Store", "123 Test St", "Test City", "TS", "Test Country");
        store.setId(UUID.randomUUID()); // Simulate what Hibernate would do
        
        // Create product
        Product product = new Product();
        product.setName("Test Product");
        product.setSku("TEST-001");
        product.setOriginalPrice(BigDecimal.valueOf(10.00));
        product.setOwnerSetSellPrice(BigDecimal.valueOf(12.00));
        product.setRetailPrice(BigDecimal.valueOf(15.00));
        product.setQuantity(100);
        product.setStore(store);
        
        // UUID should be null before persistence (generated by Hibernate)
        assertNull(product.getId(), "UUID should be null before persistence");
        
        // Manually set UUID to simulate what Hibernate would do
        UUID testUuid = UUID.randomUUID();
        product.setId(testUuid);
        
        // Verify UUID is set and valid
        assertNotNull(product.getId());
        assertEquals(testUuid, product.getId());
        assertTrue(product.getId() instanceof UUID);
        
        // Verify UUID format is valid
        String uuidString = product.getId().toString();
        assertTrue(uuidString.matches("^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"));
        
        // Verify store relationship
        assertEquals(store, product.getStore());
        assertEquals(store.getId(), product.getStore().getId());
    }

    @Test
    public void testProductConstructorWithStore() {
        Store store = new Store();
        store.setStoreName("Constructor Test Store");
        store.setAddress("456 Test Ave");
        store.setCity("Test City");
        store.setState("TS");
        store.setCountry("Test Country");
        store.setId(UUID.randomUUID()); // Simulate persisted state
        
        Product product = new Product("Constructor Product", "CONS-001", 
                BigDecimal.valueOf(5.00), BigDecimal.valueOf(8.00), 
                BigDecimal.valueOf(10.00), 25, store);
        
        // UUID should be null before persistence
        assertNull(product.getId(), "UUID should be null before persistence");
        
        // Simulate what Hibernate would do
        product.setId(UUID.randomUUID());
        
        // Verify all properties are set correctly
        assertNotNull(product.getId());
        assertTrue(product.getId() instanceof UUID);
        assertEquals("Constructor Product", product.getName());
        assertEquals("CONS-001", product.getSku());
        assertEquals(store, product.getStore());
        assertEquals(BigDecimal.valueOf(5.00), product.getOriginalPrice());
        assertEquals(BigDecimal.valueOf(8.00), product.getOwnerSetSellPrice());
        assertEquals(BigDecimal.valueOf(10.00), product.getRetailPrice());
        assertEquals(Integer.valueOf(25), product.getQuantity());
    }

    @Test
    public void testUuidUniqueness() {
        // Create multiple stores and products to verify UUID uniqueness
        Store store1 = new Store();
        Store store2 = new Store();
        Product product1 = new Product();
        Product product2 = new Product();
        
        // Simulate what Hibernate would do - generate unique UUIDs
        store1.setId(UUID.randomUUID());
        store2.setId(UUID.randomUUID());
        product1.setId(UUID.randomUUID());
        product2.setId(UUID.randomUUID());
        
        // All UUIDs should be different
        assertNotEquals(store1.getId(), store2.getId());
        assertNotEquals(product1.getId(), product2.getId());
        assertNotEquals(store1.getId(), product1.getId());
        assertNotEquals(store2.getId(), product2.getId());
    }
}