package com.pos.inventsight.model.sql;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotNull;
import org.hibernate.annotations.GenericGenerator;

import java.time.LocalDateTime;
import java.util.UUID;

/**
 * Many-to-many mapping entity for roles per company/store membership.
 * Allows multiple roles per (user, company[, store]) via separate records.
 */
@Entity
@Table(name = "company_store_user_roles",
       uniqueConstraints = @UniqueConstraint(columnNames = {"company_store_user_id", "role"}))
public class CompanyStoreUserRole {
    
    @Id
    @GeneratedValue(generator = "UUID")
    @GenericGenerator(name = "UUID", strategy = "org.hibernate.id.UUIDGenerator")
    @Column(name = "id", updatable = false, nullable = false, columnDefinition = "UUID")
    private UUID id;
    
    @NotNull
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "company_store_user_id", nullable = false)
    private CompanyStoreUser companyStoreUser;
    
    @NotNull
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 50)
    private CompanyRole role;
    
    @Column(name = "is_active")
    private Boolean isActive = true;
    
    @Column(name = "assigned_at")
    private LocalDateTime assignedAt = LocalDateTime.now();
    
    @Column(name = "assigned_by", length = 100)
    private String assignedBy;
    
    @Column(name = "revoked_at")
    private LocalDateTime revokedAt;
    
    @Column(name = "revoked_by", length = 100)
    private String revokedBy;
    
    @Column(name = "created_at")
    private LocalDateTime createdAt = LocalDateTime.now();
    
    @Column(name = "updated_at")
    private LocalDateTime updatedAt = LocalDateTime.now();
    
    // Constructors
    public CompanyStoreUserRole() {
        // UUID will be generated by Hibernate
    }
    
    public CompanyStoreUserRole(CompanyStoreUser companyStoreUser, CompanyRole role) {
        this();
        this.companyStoreUser = companyStoreUser;
        this.role = role;
    }
    
    public CompanyStoreUserRole(CompanyStoreUser companyStoreUser, CompanyRole role, String assignedBy) {
        this();
        this.companyStoreUser = companyStoreUser;
        this.role = role;
        this.assignedBy = assignedBy;
    }
    
    // Getters and Setters
    public UUID getId() { return id; }
    public void setId(UUID id) { this.id = id; }
    
    public CompanyStoreUser getCompanyStoreUser() { return companyStoreUser; }
    public void setCompanyStoreUser(CompanyStoreUser companyStoreUser) { this.companyStoreUser = companyStoreUser; }
    
    public CompanyRole getRole() { return role; }
    public void setRole(CompanyRole role) { this.role = role; }
    
    public Boolean getIsActive() { return isActive; }
    public void setIsActive(Boolean isActive) { this.isActive = isActive; }
    
    public LocalDateTime getAssignedAt() { return assignedAt; }
    public void setAssignedAt(LocalDateTime assignedAt) { this.assignedAt = assignedAt; }
    
    public String getAssignedBy() { return assignedBy; }
    public void setAssignedBy(String assignedBy) { this.assignedBy = assignedBy; }
    
    public LocalDateTime getRevokedAt() { return revokedAt; }
    public void setRevokedAt(LocalDateTime revokedAt) { this.revokedAt = revokedAt; }
    
    public String getRevokedBy() { return revokedBy; }
    public void setRevokedBy(String revokedBy) { this.revokedBy = revokedBy; }
    
    public LocalDateTime getCreatedAt() { return createdAt; }
    public void setCreatedAt(LocalDateTime createdAt) { this.createdAt = createdAt; }
    
    public LocalDateTime getUpdatedAt() { return updatedAt; }
    public void setUpdatedAt(LocalDateTime updatedAt) { this.updatedAt = updatedAt; }
    
    // Business methods
    public void revokeRole(String revokedBy) {
        this.isActive = false;
        this.revokedAt = LocalDateTime.now();
        this.revokedBy = revokedBy;
        this.updatedAt = LocalDateTime.now();
    }
    
    public void restoreRole() {
        this.isActive = true;
        this.revokedAt = null;
        this.revokedBy = null;
        this.updatedAt = LocalDateTime.now();
    }
    
    @PreUpdate
    public void updateTimestamp() {
        this.updatedAt = LocalDateTime.now();
    }
}
