package com.pos.inventsight.model.sql;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.databind.ObjectMapper;
import jakarta.persistence.*;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import org.hibernate.annotations.GenericGenerator;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import java.util.stream.Collectors;

@Entity
@Table(name = "customers")
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class Customer {
    
    @Id
    @GeneratedValue(generator = "UUID")
    @GenericGenerator(name = "UUID", strategy = "org.hibernate.id.UUIDGenerator")
    @Column(name = "id", updatable = false, nullable = false, columnDefinition = "UUID")
    private UUID id;
    
    @Version
    @Column(name = "version")
    private Long version;
    
    @NotBlank(message = "Name is required")
    @Size(max = 200, message = "Name must not exceed 200 characters")
    @Column(name = "name", nullable = false)
    private String name;
    
    @Size(max = 20, message = "Phone number must not exceed 20 characters")
    @Column(name = "phone_number")
    private String phoneNumber;
    
    @Email(message = "Email must be valid")
    @Size(max = 100, message = "Email must not exceed 100 characters")
    @Column(name = "email")
    private String email;
    
    @NotNull(message = "Customer type is required")
    @Enumerated(EnumType.STRING)
    @Column(name = "customer_type", nullable = false)
    private CustomerType customerType = CustomerType.GUEST;
    
    @Column(name = "notes", columnDefinition = "TEXT")
    private String notes;
    
    @Column(name = "discount_percentage", precision = 5, scale = 2)
    private BigDecimal discountPercentage = BigDecimal.ZERO;
    
    @Column(name = "total_purchases", precision = 12, scale = 2)
    private BigDecimal totalPurchases = BigDecimal.ZERO;
    
    // Address Fields
    @Size(max = 200, message = "Address must not exceed 200 characters")
    @Column(name = "address")
    private String address;
    
    @Size(max = 100, message = "City must not exceed 100 characters")
    @Column(name = "city")
    private String city;
    
    @Size(max = 100, message = "State must not exceed 100 characters")
    @Column(name = "state")
    private String state;
    
    @Size(max = 20, message = "Postal code must not exceed 20 characters")
    @Column(name = "postal_code")
    private String postalCode;
    
    @Size(max = 100, message = "Country must not exceed 100 characters")
    @Column(name = "country")
    private String country;
    
    // Location tracking
    @Column(name = "latitude", precision = 10, scale = 7)
    private BigDecimal latitude;
    
    @Column(name = "longitude", precision = 10, scale = 7)
    private BigDecimal longitude;
    
    // Browsing history (JSON array of product UUIDs)
    @Column(name = "recently_browsed_items", columnDefinition = "TEXT")
    private String recentlyBrowsedItems;
    
    @Column(name = "last_browsed_at")
    private LocalDateTime lastBrowsedAt;
    
    // Purchase tracking
    @Column(name = "last_purchase_date")
    private LocalDateTime lastPurchaseDate;
    
    // Relationship to receipts
    @OneToMany(mappedBy = "customer", fetch = FetchType.LAZY)
    @JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
    private List<Sale> receipts;
    
    // Multi-tenant Fields
    @NotNull(message = "Company is required")
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "company_id", nullable = false)
    @JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
    private Company company;
    
    // Optional Store Association
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "store_id")
    @JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
    private Store store;
    
    @NotNull(message = "Creator is required")
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "created_by", nullable = false)
    @JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
    private User createdByUser;
    
    // Status
    @Column(name = "is_active")
    private Boolean isActive = true;
    
    // Timestamps
    @Column(name = "created_at")
    private LocalDateTime createdAt = LocalDateTime.now();
    
    @Column(name = "updated_at")
    private LocalDateTime updatedAt = LocalDateTime.now();
    
    @Column(name = "deleted_at")
    private LocalDateTime deletedAt;
    
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "deleted_by")
    @JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
    private User deletedByUser;
    
    // Constructors
    public Customer() {
        // UUID will be generated by Hibernate
    }
    
    public Customer(String name, Company company, User createdByUser, CustomerType customerType) {
        this();
        this.name = name;
        this.company = company;
        this.createdByUser = createdByUser;
        this.customerType = customerType;
    }
    
    // Getters and Setters
    public UUID getId() { return id; }
    public void setId(UUID id) { this.id = id; }
    
    public Long getVersion() { return version; }
    public void setVersion(Long version) { this.version = version; }
    
    public String getName() { return name; }
    public void setName(String name) { this.name = name; }
    
    public String getPhoneNumber() { return phoneNumber; }
    public void setPhoneNumber(String phoneNumber) { this.phoneNumber = phoneNumber; }
    
    public String getEmail() { return email; }
    public void setEmail(String email) { this.email = email; }
    
    public CustomerType getCustomerType() { return customerType; }
    public void setCustomerType(CustomerType customerType) { this.customerType = customerType; }
    
    public String getNotes() { return notes; }
    public void setNotes(String notes) { this.notes = notes; }
    
    public BigDecimal getDiscountPercentage() { return discountPercentage; }
    public void setDiscountPercentage(BigDecimal discountPercentage) { 
        this.discountPercentage = discountPercentage != null ? discountPercentage : BigDecimal.ZERO;
    }
    
    public BigDecimal getTotalPurchases() { return totalPurchases; }
    public void setTotalPurchases(BigDecimal totalPurchases) { 
        this.totalPurchases = totalPurchases != null ? totalPurchases : BigDecimal.ZERO;
    }
    
    public String getAddress() { return address; }
    public void setAddress(String address) { this.address = address; }
    
    public String getCity() { return city; }
    public void setCity(String city) { this.city = city; }
    
    public String getState() { return state; }
    public void setState(String state) { this.state = state; }
    
    public String getPostalCode() { return postalCode; }
    public void setPostalCode(String postalCode) { this.postalCode = postalCode; }
    
    public String getCountry() { return country; }
    public void setCountry(String country) { this.country = country; }
    
    public Company getCompany() { return company; }
    public void setCompany(Company company) { this.company = company; }
    
    public Store getStore() { return store; }
    public void setStore(Store store) { this.store = store; }
    
    public User getCreatedByUser() { return createdByUser; }
    public void setCreatedByUser(User createdByUser) { this.createdByUser = createdByUser; }
    
    public Boolean getIsActive() { return isActive; }
    public void setIsActive(Boolean isActive) { this.isActive = isActive; }
    
    public LocalDateTime getCreatedAt() { return createdAt; }
    public void setCreatedAt(LocalDateTime createdAt) { this.createdAt = createdAt; }
    
    public LocalDateTime getUpdatedAt() { return updatedAt; }
    public void setUpdatedAt(LocalDateTime updatedAt) { this.updatedAt = updatedAt; }
    
    public LocalDateTime getDeletedAt() { return deletedAt; }
    public void setDeletedAt(LocalDateTime deletedAt) { this.deletedAt = deletedAt; }
    
    public User getDeletedByUser() { return deletedByUser; }
    public void setDeletedByUser(User deletedByUser) { this.deletedByUser = deletedByUser; }
    
    public BigDecimal getLatitude() { return latitude; }
    public void setLatitude(BigDecimal latitude) { this.latitude = latitude; }
    
    public BigDecimal getLongitude() { return longitude; }
    public void setLongitude(BigDecimal longitude) { this.longitude = longitude; }
    
    public String getRecentlyBrowsedItems() { return recentlyBrowsedItems; }
    public void setRecentlyBrowsedItems(String recentlyBrowsedItems) { this.recentlyBrowsedItems = recentlyBrowsedItems; }
    
    public LocalDateTime getLastBrowsedAt() { return lastBrowsedAt; }
    public void setLastBrowsedAt(LocalDateTime lastBrowsedAt) { this.lastBrowsedAt = lastBrowsedAt; }
    
    public LocalDateTime getLastPurchaseDate() { return lastPurchaseDate; }
    public void setLastPurchaseDate(LocalDateTime lastPurchaseDate) { this.lastPurchaseDate = lastPurchaseDate; }
    
    public List<Sale> getReceipts() { return receipts; }
    public void setReceipts(List<Sale> receipts) { this.receipts = receipts; }
    
    @PreUpdate
    public void updateTimestamp() {
        this.updatedAt = LocalDateTime.now();
    }
    
    /**
     * Soft delete the customer
     */
    public void softDelete(User deletedBy) {
        this.isActive = false;
        this.deletedAt = LocalDateTime.now();
        this.deletedByUser = deletedBy;
    }
    
    /**
     * Add a purchase amount to total purchases
     */
    public void addPurchase(BigDecimal amount) {
        if (amount != null && amount.compareTo(BigDecimal.ZERO) > 0) {
            this.totalPurchases = this.totalPurchases.add(amount);
        }
    }
    
    /**
     * Add a product to recently browsed items (max 10)
     */
    public void addToBrowsingHistory(UUID productId) {
        List<String> browsedList = parseRecentlyBrowsed();
        
        // Remove if already exists
        browsedList.remove(productId.toString());
        
        // Add to front
        browsedList.add(0, productId.toString());
        
        // Keep only last 10
        if (browsedList.size() > 10) {
            browsedList = browsedList.subList(0, 10);
        }
        
        // Convert back to JSON
        this.recentlyBrowsedItems = convertToJson(browsedList);
        this.lastBrowsedAt = LocalDateTime.now();
    }
    
    private List<String> parseRecentlyBrowsed() {
        if (recentlyBrowsedItems == null || recentlyBrowsedItems.isEmpty()) {
            return new ArrayList<>();
        }
        try {
            ObjectMapper mapper = new ObjectMapper();
            return mapper.readValue(recentlyBrowsedItems, 
                mapper.getTypeFactory().constructCollectionType(List.class, String.class));
        } catch (Exception e) {
            return new ArrayList<>();
        }
    }
    
    private String convertToJson(List<String> list) {
        try {
            ObjectMapper mapper = new ObjectMapper();
            return mapper.writeValueAsString(list);
        } catch (Exception e) {
            return "[]";
        }
    }
    
    public List<UUID> getRecentlyBrowsedProductIds() {
        return parseRecentlyBrowsed().stream()
            .map(idString -> {
                try {
                    return UUID.fromString(idString);
                } catch (IllegalArgumentException e) {
                    // Skip invalid UUID strings
                    return null;
                }
            })
            .filter(uuid -> uuid != null)
            .collect(Collectors.toList());
    }
    
    /**
     * Customer type enum
     */
    public enum CustomerType {
        GUEST,
        REGISTERED
    }
}
