package com.pos.inventsight.model.sql;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import org.hibernate.annotations.GenericGenerator;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.UUID;

@Entity
@Table(name = "predefined_items", 
       uniqueConstraints = @UniqueConstraint(
           name = "unique_item_per_company", 
           columnNames = {"company_id", "name", "unit_type"}
       ))
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class PredefinedItem {
    
    @Id
    @GeneratedValue(generator = "UUID")
    @GenericGenerator(name = "UUID", strategy = "org.hibernate.id.UUIDGenerator")
    @Column(name = "id", updatable = false, nullable = false, columnDefinition = "UUID")
    private UUID id;
    
    @NotBlank(message = "Name is required")
    @Size(max = 255, message = "Name must not exceed 255 characters")
    @Column(name = "name", nullable = false)
    private String name;
    
    @Size(max = 11, message = "SKU must be 11 digits")
    @Column(name = "sku", length = 11)
    private String sku;
    
    @Size(max = 100, message = "Category must not exceed 100 characters")
    @Column(name = "category")
    private String category;
    
    @NotBlank(message = "Unit type is required")
    @Size(max = 50, message = "Unit type must not exceed 50 characters")
    @Column(name = "unit_type", nullable = false)
    private String unitType;
    
    @Column(name = "description", columnDefinition = "TEXT")
    private String description;
    
    @Column(name = "default_price", precision = 10, scale = 2)
    private BigDecimal defaultPrice;
    
    // Multi-tenant Fields
    @NotNull(message = "Company is required")
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "company_id", nullable = false)
    @JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
    private Company company;
    
    @NotNull(message = "Creator is required")
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "created_by", nullable = false)
    @JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
    private User createdByUser;
    
    // Status
    @Column(name = "is_active")
    private Boolean isActive = true;
    
    // Timestamps
    @Column(name = "created_at")
    private LocalDateTime createdAt = LocalDateTime.now();
    
    @Column(name = "updated_at")
    private LocalDateTime updatedAt = LocalDateTime.now();
    
    @Column(name = "deleted_at")
    private LocalDateTime deletedAt;
    
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "deleted_by")
    @JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
    private User deletedByUser;
    
    // Constructors
    public PredefinedItem() {
        // UUID will be generated by Hibernate
    }
    
    public PredefinedItem(String name, String unitType, Company company, User createdByUser) {
        this();
        this.name = name;
        this.unitType = unitType;
        this.company = company;
        this.createdByUser = createdByUser;
    }
    
    // Getters and Setters
    public UUID getId() { return id; }
    public void setId(UUID id) { this.id = id; }
    
    public String getName() { return name; }
    public void setName(String name) { this.name = name; }
    
    public String getSku() { return sku; }
    public void setSku(String sku) { this.sku = sku; }
    
    public String getCategory() { return category; }
    public void setCategory(String category) { this.category = category; }
    
    public String getUnitType() { return unitType; }
    public void setUnitType(String unitType) { this.unitType = unitType; }
    
    public String getDescription() { return description; }
    public void setDescription(String description) { this.description = description; }
    
    public BigDecimal getDefaultPrice() { return defaultPrice; }
    public void setDefaultPrice(BigDecimal defaultPrice) { this.defaultPrice = defaultPrice; }
    
    public Company getCompany() { return company; }
    public void setCompany(Company company) { this.company = company; }
    
    public User getCreatedByUser() { return createdByUser; }
    public void setCreatedByUser(User createdByUser) { this.createdByUser = createdByUser; }
    
    public Boolean getIsActive() { return isActive; }
    public void setIsActive(Boolean isActive) { this.isActive = isActive; }
    
    public LocalDateTime getCreatedAt() { return createdAt; }
    public void setCreatedAt(LocalDateTime createdAt) { this.createdAt = createdAt; }
    
    public LocalDateTime getUpdatedAt() { return updatedAt; }
    public void setUpdatedAt(LocalDateTime updatedAt) { this.updatedAt = updatedAt; }
    
    public LocalDateTime getDeletedAt() { return deletedAt; }
    public void setDeletedAt(LocalDateTime deletedAt) { this.deletedAt = deletedAt; }
    
    public User getDeletedByUser() { return deletedByUser; }
    public void setDeletedByUser(User deletedByUser) { this.deletedByUser = deletedByUser; }
    
    @PreUpdate
    public void updateTimestamp() {
        this.updatedAt = LocalDateTime.now();
    }
    
    /**
     * Soft delete the item
     */
    public void softDelete(User deletedBy) {
        this.isActive = false;
        this.deletedAt = LocalDateTime.now();
        this.deletedByUser = deletedBy;
    }
}
