package com.pos.inventsight.model.sql;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import jakarta.persistence.*;
import jakarta.validation.constraints.NotNull;
import org.hibernate.annotations.GenericGenerator;

import java.time.LocalDateTime;
import java.util.UUID;

@Entity
@Table(name = "predefined_item_warehouses",
       uniqueConstraints = @UniqueConstraint(
           name = "unique_item_warehouse",
           columnNames = {"predefined_item_id", "warehouse_id"}
       ))
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class PredefinedItemWarehouse {
    
    @Id
    @GeneratedValue(generator = "UUID")
    @GenericGenerator(name = "UUID", strategy = "org.hibernate.id.UUIDGenerator")
    @Column(name = "id", updatable = false, nullable = false, columnDefinition = "UUID")
    private UUID id;
    
    @NotNull(message = "Predefined item is required")
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "predefined_item_id", nullable = false)
    @JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
    private PredefinedItem predefinedItem;
    
    @NotNull(message = "Warehouse is required")
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "warehouse_id", nullable = false)
    @JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
    private Warehouse warehouse;
    
    @Column(name = "created_at")
    private LocalDateTime createdAt = LocalDateTime.now();
    
    @NotNull(message = "Creator is required")
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "created_by", nullable = false)
    @JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
    private User createdByUser;
    
    // Constructors
    public PredefinedItemWarehouse() {
        // UUID will be generated by Hibernate
    }
    
    public PredefinedItemWarehouse(PredefinedItem predefinedItem, Warehouse warehouse, User createdByUser) {
        this();
        this.predefinedItem = predefinedItem;
        this.warehouse = warehouse;
        this.createdByUser = createdByUser;
    }
    
    // Getters and Setters
    public UUID getId() { return id; }
    public void setId(UUID id) { this.id = id; }
    
    public PredefinedItem getPredefinedItem() { return predefinedItem; }
    public void setPredefinedItem(PredefinedItem predefinedItem) { this.predefinedItem = predefinedItem; }
    
    public Warehouse getWarehouse() { return warehouse; }
    public void setWarehouse(Warehouse warehouse) { this.warehouse = warehouse; }
    
    public LocalDateTime getCreatedAt() { return createdAt; }
    public void setCreatedAt(LocalDateTime createdAt) { this.createdAt = createdAt; }
    
    public User getCreatedByUser() { return createdByUser; }
    public void setCreatedByUser(User createdByUser) { this.createdByUser = createdByUser; }
}
