package com.pos.inventsight.model.sql;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import jakarta.persistence.*;
import jakarta.validation.constraints.NotNull;
import org.hibernate.annotations.GenericGenerator;

import java.time.LocalDateTime;
import java.util.UUID;

@Entity
@Table(name = "predefined_item_stores",
       uniqueConstraints = @UniqueConstraint(
           name = "unique_item_store",
           columnNames = {"predefined_item_id", "store_id"}
       ))
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class PredefinedItemStore {
    
    @Id
    @GeneratedValue(generator = "UUID")
    @GenericGenerator(name = "UUID", strategy = "org.hibernate.id.UUIDGenerator")
    @Column(name = "id", updatable = false, nullable = false, columnDefinition = "UUID")
    private UUID id;
    
    @NotNull(message = "Predefined item is required")
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "predefined_item_id", nullable = false)
    @JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
    private PredefinedItem predefinedItem;
    
    @NotNull(message = "Store is required")
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "store_id", nullable = false)
    @JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
    private Store store;
    
    @Column(name = "created_at")
    private LocalDateTime createdAt = LocalDateTime.now();
    
    @NotNull(message = "Creator is required")
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "created_by", nullable = false)
    @JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
    private User createdByUser;
    
    // Constructors
    public PredefinedItemStore() {
        // UUID will be generated by Hibernate
    }
    
    public PredefinedItemStore(PredefinedItem predefinedItem, Store store, User createdByUser) {
        this();
        this.predefinedItem = predefinedItem;
        this.store = store;
        this.createdByUser = createdByUser;
    }
    
    // Getters and Setters
    public UUID getId() { return id; }
    public void setId(UUID id) { this.id = id; }
    
    public PredefinedItem getPredefinedItem() { return predefinedItem; }
    public void setPredefinedItem(PredefinedItem predefinedItem) { this.predefinedItem = predefinedItem; }
    
    public Store getStore() { return store; }
    public void setStore(Store store) { this.store = store; }
    
    public LocalDateTime getCreatedAt() { return createdAt; }
    public void setCreatedAt(LocalDateTime createdAt) { this.createdAt = createdAt; }
    
    public User getCreatedByUser() { return createdByUser; }
    public void setCreatedByUser(User createdByUser) { this.createdByUser = createdByUser; }
}
